### ISSUE TITLE
Velocity 1.18 Support

### ISSUE THREAD

**Issue by weihao** [itzg/docker-bungeecord#81] opened 2021-12-01 01:46 UTC
Tracking 1.18 proxy server support

**Comment by itzg** [comment] 2021-12-01 02:38
The image isn't tied to any particular version. What are you wanting to track exactly?

**Comment by weihao** [comment] 2021-12-01 03:02
@itzg  `VELOCITY_VERSION: "latest"` only pulls the 1.17 version currently. I want to track when it support 1.18

**Comment by itzg** [comment] 2021-12-01 12:57
Now I'm really confused. Velocity is a proxy and doesn't need to track the Minecraft versions such as 1.18. Their latest is 3.1.0:

https://velocitypowered.com/downloads

**Comment by itzg** [comment] 2021-12-01 15:23
Aha, the solution was discovered in https://github.com/itzg/docker-bungeecord/issues/82

**Comment by finndo77** [comment] 2021-12-01 15:29
The issue is that Velocity "pretends" to be the newest client version it is aware of when connecting to a Minecraft server, since they moved their repo, the version we have been pulling down is pretending to be 1.17.x  so it gives an Outdated client error when connecting to 1.18.

I wish I had figured this out a month ago, I could have posted it here then, but I just found out they moved their repo about an hour ago.  They had mentioned they were migrating, but I saw no other info and was hoping they would wait until AFTER a major Minecraft update to change everything.  (especially since I just switched to Velocity in November after testing it in Oct...)

**Comment by weihao** [comment] 2021-12-01 22:21
> 


I am able to reproduce this:

**Comment by itzg** [comment] 2021-12-02 00:20
> The issue is that Velocity "pretends" to be the newest client version it is aware of when connecting to a Minecraft server, since they moved their repo, the version we have been pulling down is pretending to be 1.17.x so it gives an Outdated client error when connecting to 1.18.

Thanks for the clarification. That totally makes sense now.

**Comment by itzg** [comment] 2021-12-02 00:20
I'm going to close this and consolidate discussion onto #82

**Closed by itzg** 2021-12-02 00:20 UTC
